name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade uv

      - name: Cache uv packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('uv.lock', 'requirements.txt') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Create venv with uv
        run: |
          uv venv --python python${{ matrix.python-version }}
          source .venv/bin/activate
          # Install project deps (+ pytest if not already in requirements)
          if [ -f requirements.txt ]; then
            uv pip install -r requirements.txt
          fi
          uv pip install pytest

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
